"""add phase 5 progress tracking

Revision ID: 72c6315c31e9
Revises: c2b979c2de7e
Create Date: 2026-07-15 01:17:47.869747
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '72c6315c31e9'
down_revision = 'c2b979c2de7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('client_record_id', sa.String(length=180), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('waist_in', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('chest_in', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('arm_in', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('thigh_in', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.String(length=24), server_default='manual', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arm_in IS NULL OR (arm_in > 4 AND arm_in < 40)', name='ck_body_measurements_arm_bounds'),
    sa.CheckConstraint('chest_in IS NULL OR (chest_in > 10 AND chest_in < 100)', name='ck_body_measurements_chest_bounds'),
    sa.CheckConstraint('thigh_in IS NULL OR (thigh_in > 8 AND thigh_in < 60)', name='ck_body_measurements_thigh_bounds'),
    sa.CheckConstraint('waist_in IS NULL OR (waist_in > 10 AND waist_in < 100)', name='ck_body_measurements_waist_bounds'),
    sa.CheckConstraint('weight_kg IS NOT NULL OR waist_in IS NOT NULL OR chest_in IS NOT NULL OR arm_in IS NOT NULL OR thigh_in IS NOT NULL', name='ck_body_measurements_one_value'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg > 20 AND weight_kg < 350)', name='ck_body_measurements_weight_bounds'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_record_id', name='uq_body_measurements_user_client_record')
    )
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_index('ix_body_measurements_user_local_date', 'body_measurements', ['user_id', 'local_date'], unique=False)
    op.create_index('ix_body_measurements_user_measured_at', 'body_measurements', ['user_id', 'measured_at'], unique=False)
    op.create_table('generated_reports',
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('storage_key', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='generated', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_type', 'period_start', 'period_end', name='uq_generated_reports_user_type_period')
    )
    op.create_index('ix_generated_reports_user_created_at', 'generated_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generated_reports_user_id'), 'generated_reports', ['user_id'], unique=False)
    op.create_table('progress_milestones',
    sa.Column('milestone_type', sa.String(length=80), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'milestone_type', 'threshold_value', name='uq_progress_milestones_user_type_threshold')
    )
    op.create_index('ix_progress_milestones_user_achieved_at', 'progress_milestones', ['user_id', 'achieved_at'], unique=False)
    op.create_index(op.f('ix_progress_milestones_user_id'), 'progress_milestones', ['user_id'], unique=False)
    op.create_table('weekly_check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_record_id', sa.String(length=180), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('energy', sa.String(length=24), nullable=True),
    sa.Column('hunger', sa.String(length=24), nullable=True),
    sa.Column('digestion', sa.String(length=24), nullable=True),
    sa.Column('average_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('private_note', sa.Text(), nullable=True),
    sa.Column('measurement_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("digestion is null or digestion in ('good', 'some_gas', 'difficult')", name='ck_weekly_check_ins_digestion'),
    sa.CheckConstraint("energy is null or energy in ('low', 'normal', 'high')", name='ck_weekly_check_ins_energy'),
    sa.CheckConstraint("hunger is null or hunger in ('low', 'normal', 'high')", name='ck_weekly_check_ins_hunger'),
    sa.CheckConstraint("status in ('draft', 'completed')", name='ck_weekly_check_ins_status'),
    sa.ForeignKeyConstraint(['measurement_id'], ['body_measurements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_record_id', name='uq_weekly_check_ins_user_client_record')
    )
    op.create_index(op.f('ix_weekly_check_ins_user_id'), 'weekly_check_ins', ['user_id'], unique=False)
    op.create_index('ix_weekly_check_ins_user_week_status', 'weekly_check_ins', ['user_id', 'week_number', 'status'], unique=False)
    op.create_index('uq_weekly_check_ins_user_completed_week', 'weekly_check_ins', ['user_id', 'week_number'], unique=True, postgresql_where=sa.text("status = 'completed' AND deleted_at IS NULL"))
    op.create_table('progress_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('check_in_id', sa.UUID(), nullable=False),
    sa.Column('pose', sa.String(length=12), nullable=False),
    sa.Column('storage_key', sa.String(length=240), nullable=False),
    sa.Column('processed_mime_type', sa.String(length=80), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("pose in ('front', 'side', 'back')", name='ck_progress_photos_pose'),
    sa.CheckConstraint('width > 0 AND height > 0 AND size_bytes > 0', name='ck_progress_photos_positive_media'),
    sa.ForeignKeyConstraint(['check_in_id'], ['weekly_check_ins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_check_in_id'), 'progress_photos', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'], unique=False)
    op.create_index('uq_progress_photos_user_check_in_pose_active', 'progress_photos', ['user_id', 'check_in_id', 'pose'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_progress_photos_user_check_in_pose_active', table_name='progress_photos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_check_in_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index('uq_weekly_check_ins_user_completed_week', table_name='weekly_check_ins', postgresql_where=sa.text("status = 'completed' AND deleted_at IS NULL"))
    op.drop_index('ix_weekly_check_ins_user_week_status', table_name='weekly_check_ins')
    op.drop_index(op.f('ix_weekly_check_ins_user_id'), table_name='weekly_check_ins')
    op.drop_table('weekly_check_ins')
    op.drop_index(op.f('ix_progress_milestones_user_id'), table_name='progress_milestones')
    op.drop_index('ix_progress_milestones_user_achieved_at', table_name='progress_milestones')
    op.drop_table('progress_milestones')
    op.drop_index(op.f('ix_generated_reports_user_id'), table_name='generated_reports')
    op.drop_index('ix_generated_reports_user_created_at', table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('ix_body_measurements_user_measured_at', table_name='body_measurements')
    op.drop_index('ix_body_measurements_user_local_date', table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
