"""align model indexes

Revision ID: c2b979c2de7e
Revises: 20260714_0001
Create Date: 2026-07-15 00:25:41.078578
"""
from alembic import op


revision = 'c2b979c2de7e'
down_revision = '20260714_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_daily_tracking_user_id'), 'daily_tracking', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_migration_batches_user_id'), 'migration_batches', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_devices_user_id'), 'sync_devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_mutations_user_id'), 'sync_mutations', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_sync_mutations_user_id'), table_name='sync_mutations')
    op.drop_index(op.f('ix_sync_devices_user_id'), table_name='sync_devices')
    op.drop_index(op.f('ix_migration_batches_user_id'), table_name='migration_batches')
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_daily_tracking_user_id'), table_name='daily_tracking')
    # ### end Alembic commands ###
